-- 기간계 모사 테이블: 실제 스키마 확인 결과 기준 (legacy-schema-notes.md)
-- Oracle 19c 호환. query1/query2 + DML월별조회쿼리가 참조하는 컬럼만 포함.

CREATE TABLE TBCPPE091M00 (
  SR_NO            VARCHAR2(11),
  SRNO             NUMBER,
  SR_TPCD          VARCHAR2(2),
  SR_DETL_TPCD     VARCHAR2(4),
  SR_REG_STAT_CODE VARCHAR2(2),
  DPCD             VARCHAR2(4),
  PRCH_DPCD        VARCHAR2(4),
  SPIC_EMPNO       VARCHAR2(9),
  PRCH_EMPNO       VARCHAR2(9),
  RQSR_EMPNO       VARCHAR2(9),
  TRTH_RQST_EMPNO  VARCHAR2(9),
  TRTH_RQST_DPCD   VARCHAR2(4),
  CUST_INFO_YN     VARCHAR2(1),
  TITL_CNTT        VARCHAR2(400),
  MSG_CNTT         VARCHAR2(4000),
  JOB_MANM         VARCHAR2(6),
  REG_DATE         VARCHAR2(8),
  RFLC_SCDL_DATE   VARCHAR2(8),
  PROS_CMPT_DATE   VARCHAR2(8),
  MNPL_EMPNO       VARCHAR2(20)
);

CREATE TABLE TBCPPE093L00 (
  SR_NO        VARCHAR2(11),
  SRNO         NUMBER,
  SPIC_EMPNO   VARCHAR2(9),
  JOB_EXEC_HOUR VARCHAR2(6),
  JOB_MANM     VARCHAR2(6),
  FIN_DATE     VARCHAR2(8),
  APRV_YN      VARCHAR2(1),
  MNPL_EMPNO   VARCHAR2(20)
);

-- 097: 복합 PK (SR_TPCD, SR_DETL_TPCD)
CREATE TABLE TBCPPE097L00 (
  SR_TPCD      VARCHAR2(2),
  SR_DETL_TPCD VARCHAR2(4),
  SR_TPCD_NAME VARCHAR2(40),
  USE_YN       VARCHAR2(1)
);

-- 이하 DML월별조회쿼리 참조 테이블 (인사/부서/업무상세분류)

-- 인사 기본: 사번 → 이름/소속부서
CREATE TABLE TBCPPU001I00 (
  EMPNO     VARCHAR2(9),
  FLNM      VARCHAR2(40),
  BLNG_DPCD VARCHAR2(4)
);

-- 부서 마스터: 부서코드 → 부서명
CREATE TABLE TBCPPD001M00 (
  DPCD VARCHAR2(4),
  DPNM VARCHAR2(40)
);

-- SR 업무상세분류 매핑
CREATE TABLE TBCPPE091D02 (
  SR_NO             VARCHAR2(11),
  SR_BSWR_DETL_DVCD VARCHAR2(6)
);

-- 업무상세분류 코드명
CREATE TABLE TBCPPE108C01 (
  SR_BSWR_DETL_DVCD     VARCHAR2(6),
  SR_BSWR_DETL_DIV_NAME VARCHAR2(100)
);
