-- V001: 공통코드 / 인력 마스터 (DB2, Oracle 19c 호환)
CREATE TABLE CD_COMMON (
  GRP_CD     VARCHAR2(30)  NOT NULL,
  CD_VAL     VARCHAR2(30)  NOT NULL,
  CD_NM      VARCHAR2(100) NOT NULL,
  SORT_NO    NUMBER(5)     DEFAULT 0 NOT NULL,
  USE_YN     CHAR(1)       DEFAULT 'Y' NOT NULL,
  CREATED_AT TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  CREATED_BY VARCHAR2(30)  DEFAULT 'SYSTEM' NOT NULL,
  UPDATED_AT TIMESTAMP,
  UPDATED_BY VARCHAR2(30),
  CONSTRAINT PK_CD_COMMON PRIMARY KEY (GRP_CD, CD_VAL),
  CONSTRAINT CK_CD_COMMON_USE_YN CHECK (USE_YN IN ('Y','N'))
);

CREATE TABLE HR_DEVELOPER (
  EMPNO      VARCHAR2(20)  NOT NULL,
  EMP_NM     VARCHAR2(50)  NOT NULL,
  DEPT_CD    VARCHAR2(30),
  PART_CD    VARCHAR2(30),
  GRADE_CD   VARCHAR2(30),
  ROLE_CD    VARCHAR2(30),
  DEV_YN     CHAR(1)       DEFAULT 'Y' NOT NULL,
  STATUS_CD  VARCHAR2(10)  DEFAULT '재직' NOT NULL,
  CREATED_AT TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  CREATED_BY VARCHAR2(30)  DEFAULT 'SYSTEM' NOT NULL,
  UPDATED_AT TIMESTAMP,
  UPDATED_BY VARCHAR2(30),
  CONSTRAINT PK_HR_DEVELOPER PRIMARY KEY (EMPNO),
  CONSTRAINT CK_HR_DEV_YN CHECK (DEV_YN IN ('Y','N')),
  CONSTRAINT CK_HR_STATUS CHECK (STATUS_CD IN ('재직','휴직'))
);

CREATE INDEX IX_HR_DEVELOPER_PART ON HR_DEVELOPER (PART_CD);
