-- V002: 공통코드 / 인력 시드
INSERT INTO CD_COMMON (GRP_CD, CD_VAL, CD_NM, SORT_NO) VALUES ('SR_TPCD','1','개발요청',1);
INSERT INTO CD_COMMON (GRP_CD, CD_VAL, CD_NM, SORT_NO) VALUES ('SR_TPCD','2','유지보수',2);
INSERT INTO CD_COMMON (GRP_CD, CD_VAL, CD_NM, SORT_NO) VALUES ('SR_TPCD','3','자료요청',3);
INSERT INTO CD_COMMON (GRP_CD, CD_VAL, CD_NM, SORT_NO) VALUES ('SR_TPCD','5','인프라SR',4);
INSERT INTO CD_COMMON (GRP_CD, CD_VAL, CD_NM, SORT_NO) VALUES ('SR_TPCD','17','고객안내 발송',5);
INSERT INTO CD_COMMON (GRP_CD, CD_VAL, CD_NM, SORT_NO) VALUES ('SR_TPCD','18','데이타변경',6);
INSERT INTO CD_COMMON (GRP_CD, CD_VAL, CD_NM, SORT_NO) VALUES ('SR_TPCD','19','원장변경',7);

INSERT INTO CD_COMMON (GRP_CD, CD_VAL, CD_NM, SORT_NO) VALUES ('EMP_ROLE','01','팀장',1);
INSERT INTO CD_COMMON (GRP_CD, CD_VAL, CD_NM, SORT_NO) VALUES ('EMP_ROLE','02','업무리더',2);
INSERT INTO CD_COMMON (GRP_CD, CD_VAL, CD_NM, SORT_NO) VALUES ('EMP_ROLE','03','일반직원',3);

INSERT INTO CD_COMMON (GRP_CD, CD_VAL, CD_NM, SORT_NO) VALUES ('EMP_STATUS','재직','재직',1);
INSERT INTO CD_COMMON (GRP_CD, CD_VAL, CD_NM, SORT_NO) VALUES ('EMP_STATUS','휴직','휴직',2);

INSERT INTO HR_DEVELOPER (EMPNO, EMP_NM, DEPT_CD, PART_CD, GRADE_CD, ROLE_CD, DEV_YN, STATUS_CD)
  VALUES ('E0001','김팀장','D101','P01','부장','01','N','재직');
INSERT INTO HR_DEVELOPER (EMPNO, EMP_NM, DEPT_CD, PART_CD, GRADE_CD, ROLE_CD, DEV_YN, STATUS_CD)
  VALUES ('E0002','이개발','D101','P01','과장','03','Y','재직');
INSERT INTO HR_DEVELOPER (EMPNO, EMP_NM, DEPT_CD, PART_CD, GRADE_CD, ROLE_CD, DEV_YN, STATUS_CD)
  VALUES ('E0003','박개발','D101','P02','대리','03','Y','재직');
INSERT INTO HR_DEVELOPER (EMPNO, EMP_NM, DEPT_CD, PART_CD, GRADE_CD, ROLE_CD, DEV_YN, STATUS_CD)
  VALUES ('E0004','최개발','D101','P02','사원','03','Y','재직');
