-- V003: 코드 일원화 (ATTR1 부가속성, EMP_STATUS 코드화, SR_CLS 매핑)
ALTER TABLE CD_COMMON ADD (ATTR1 VARCHAR2(30));

-- HR CHECK 제약 교체: 한글 → 코드('01'재직 / '02'휴직)
ALTER TABLE HR_DEVELOPER DROP CONSTRAINT CK_HR_STATUS;
UPDATE HR_DEVELOPER SET STATUS_CD = '01' WHERE STATUS_CD = '재직';
UPDATE HR_DEVELOPER SET STATUS_CD = '02' WHERE STATUS_CD = '휴직';
ALTER TABLE HR_DEVELOPER MODIFY (STATUS_CD DEFAULT '01');
ALTER TABLE HR_DEVELOPER ADD CONSTRAINT CK_HR_STATUS CHECK (STATUS_CD IN ('01','02'));

-- EMP_STATUS 코드화
UPDATE CD_COMMON SET CD_VAL='01' WHERE GRP_CD='EMP_STATUS' AND CD_VAL='재직';
UPDATE CD_COMMON SET CD_VAL='02' WHERE GRP_CD='EMP_STATUS' AND CD_VAL='휴직';

-- SR_CLS 분류 코드
INSERT INTO CD_COMMON (GRP_CD, CD_VAL, CD_NM, SORT_NO) VALUES ('SR_CLS','01','개발요청',1);
INSERT INTO CD_COMMON (GRP_CD, CD_VAL, CD_NM, SORT_NO) VALUES ('SR_CLS','02','유지보수',2);
INSERT INTO CD_COMMON (GRP_CD, CD_VAL, CD_NM, SORT_NO) VALUES ('SR_CLS','03','자료요청',3);
INSERT INTO CD_COMMON (GRP_CD, CD_VAL, CD_NM, SORT_NO) VALUES ('SR_CLS','99','기타',9);

-- SR_TPCD → SR_CLS 매핑(ATTR1). 개발요청=01, 유지보수=02, 자료요청=03, 그외=99
UPDATE CD_COMMON SET ATTR1='01' WHERE GRP_CD='SR_TPCD' AND CD_VAL='1';
UPDATE CD_COMMON SET ATTR1='02' WHERE GRP_CD='SR_TPCD' AND CD_VAL='2';
UPDATE CD_COMMON SET ATTR1='03' WHERE GRP_CD='SR_TPCD' AND CD_VAL='3';
UPDATE CD_COMMON SET ATTR1='99' WHERE GRP_CD='SR_TPCD' AND CD_VAL IN ('5','17','18','19');
