-- V005: SR_TPCD 코드값 2자리 패딩 + ATTR1(SR_CLS) 재매핑
-- V002 에서 '1','2'... 로 입력됐고, V003 ATTR1 이 '1','2','3' 에 걸려 실제 기간계(2자리)와 불일치 → 보정
UPDATE CD_COMMON SET CD_VAL='01' WHERE GRP_CD='SR_TPCD' AND CD_VAL='1';
UPDATE CD_COMMON SET CD_VAL='02' WHERE GRP_CD='SR_TPCD' AND CD_VAL='2';
UPDATE CD_COMMON SET CD_VAL='03' WHERE GRP_CD='SR_TPCD' AND CD_VAL='3';
UPDATE CD_COMMON SET CD_VAL='05' WHERE GRP_CD='SR_TPCD' AND CD_VAL='5';
-- 17,18,19 는 이미 2자리 — CD_VAL 변경 불필요

-- ATTR1 재매핑: 이미 2자리 패딩된 CD_VAL 기준으로 재설정
UPDATE CD_COMMON SET ATTR1='01' WHERE GRP_CD='SR_TPCD' AND CD_VAL='01';  -- 개발요청
UPDATE CD_COMMON SET ATTR1='02' WHERE GRP_CD='SR_TPCD' AND CD_VAL='02';  -- 유지보수
UPDATE CD_COMMON SET ATTR1='03' WHERE GRP_CD='SR_TPCD' AND CD_VAL='03';  -- 자료요청
UPDATE CD_COMMON SET ATTR1='99' WHERE GRP_CD='SR_TPCD' AND CD_VAL IN ('05','17','18','19');
