-- V006: BATCH_RUN_LOG.STATUS CHECK 제약에 'RUNNING' 추가
-- 기존 ('OK','FAIL') → ('RUNNING','OK','FAIL')
-- 배치 실행 시작 시 STATUS='RUNNING'으로 즉시 커밋하여 실행 이력 추적 가능
ALTER TABLE BATCH_RUN_LOG DROP CONSTRAINT CK_BATCH_STATUS;
ALTER TABLE BATCH_RUN_LOG ADD CONSTRAINT CK_BATCH_STATUS CHECK (STATUS IN ('RUNNING','OK','FAIL'));
