-- V007: 로그인 계정 (19c 호환). 역할/이름/파트는 HR_DEVELOPER에서.
CREATE TABLE AUTH_ACCOUNT (
  EMPNO         VARCHAR2(20)  NOT NULL,
  PASSWORD_HASH VARCHAR2(100) NOT NULL,
  PWD_RESET_YN  CHAR(1)       DEFAULT 'Y' NOT NULL,
  LAST_LOGIN_AT TIMESTAMP,
  FAIL_CNT      NUMBER(4)     DEFAULT 0 NOT NULL,
  CREATED_AT    TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  CREATED_BY    VARCHAR2(30)  DEFAULT 'SYSTEM' NOT NULL,
  UPDATED_AT    TIMESTAMP,
  UPDATED_BY    VARCHAR2(30),
  CONSTRAINT PK_AUTH_ACCOUNT PRIMARY KEY (EMPNO),
  CONSTRAINT CK_AUTH_PWD_RESET CHECK (PWD_RESET_YN IN ('Y','N'))
);
