-- V008: 부서(DEPT_CD) / 파트(PART_CD) 공통코드 시드 (멱등 MERGE — 재적용 안전)

-- 부서
MERGE INTO CD_COMMON t USING (SELECT 'DEPT_CD' g, '2139' v, 'IT개발팀'   n, 1 s FROM dual) x
  ON (t.GRP_CD=x.g AND t.CD_VAL=x.v)
  WHEN NOT MATCHED THEN INSERT (GRP_CD,CD_VAL,CD_NM,SORT_NO,USE_YN) VALUES (x.g,x.v,x.n,x.s,'Y');
MERGE INTO CD_COMMON t USING (SELECT 'DEPT_CD' g, '2735' v, 'AI솔루션팀' n, 2 s FROM dual) x
  ON (t.GRP_CD=x.g AND t.CD_VAL=x.v)
  WHEN NOT MATCHED THEN INSERT (GRP_CD,CD_VAL,CD_NM,SORT_NO,USE_YN) VALUES (x.g,x.v,x.n,x.s,'Y');
MERGE INTO CD_COMMON t USING (SELECT 'DEPT_CD' g, '2140' v, 'IT서비스팀' n, 3 s FROM dual) x
  ON (t.GRP_CD=x.g AND t.CD_VAL=x.v)
  WHEN NOT MATCHED THEN INSERT (GRP_CD,CD_VAL,CD_NM,SORT_NO,USE_YN) VALUES (x.g,x.v,x.n,x.s,'Y');

-- 파트 (P01~P10)
MERGE INTO CD_COMMON t USING (SELECT 'PART_CD' g, 'P01' v, '금융상품' n, 1 s FROM dual) x
  ON (t.GRP_CD=x.g AND t.CD_VAL=x.v) WHEN NOT MATCHED THEN INSERT (GRP_CD,CD_VAL,CD_NM,SORT_NO,USE_YN) VALUES (x.g,x.v,x.n,x.s,'Y');
MERGE INTO CD_COMMON t USING (SELECT 'PART_CD' g, 'P02' v, '계좌' n, 2 s FROM dual) x
  ON (t.GRP_CD=x.g AND t.CD_VAL=x.v) WHEN NOT MATCHED THEN INSERT (GRP_CD,CD_VAL,CD_NM,SORT_NO,USE_YN) VALUES (x.g,x.v,x.n,x.s,'Y');
MERGE INTO CD_COMMON t USING (SELECT 'PART_CD' g, 'P03' v, 'MTS' n, 3 s FROM dual) x
  ON (t.GRP_CD=x.g AND t.CD_VAL=x.v) WHEN NOT MATCHED THEN INSERT (GRP_CD,CD_VAL,CD_NM,SORT_NO,USE_YN) VALUES (x.g,x.v,x.n,x.s,'Y');
MERGE INTO CD_COMMON t USING (SELECT 'PART_CD' g, 'P04' v, 'HTS' n, 4 s FROM dual) x
  ON (t.GRP_CD=x.g AND t.CD_VAL=x.v) WHEN NOT MATCHED THEN INSERT (GRP_CD,CD_VAL,CD_NM,SORT_NO,USE_YN) VALUES (x.g,x.v,x.n,x.s,'Y');
MERGE INTO CD_COMMON t USING (SELECT 'PART_CD' g, 'P05' v, '출납' n, 5 s FROM dual) x
  ON (t.GRP_CD=x.g AND t.CD_VAL=x.v) WHEN NOT MATCHED THEN INSERT (GRP_CD,CD_VAL,CD_NM,SORT_NO,USE_YN) VALUES (x.g,x.v,x.n,x.s,'Y');
MERGE INTO CD_COMMON t USING (SELECT 'PART_CD' g, 'P06' v, '업무공통' n, 6 s FROM dual) x
  ON (t.GRP_CD=x.g AND t.CD_VAL=x.v) WHEN NOT MATCHED THEN INSERT (GRP_CD,CD_VAL,CD_NM,SORT_NO,USE_YN) VALUES (x.g,x.v,x.n,x.s,'Y');
MERGE INTO CD_COMMON t USING (SELECT 'PART_CD' g, 'P07' v, '해외주식' n, 7 s FROM dual) x
  ON (t.GRP_CD=x.g AND t.CD_VAL=x.v) WHEN NOT MATCHED THEN INSERT (GRP_CD,CD_VAL,CD_NM,SORT_NO,USE_YN) VALUES (x.g,x.v,x.n,x.s,'Y');
MERGE INTO CD_COMMON t USING (SELECT 'PART_CD' g, 'P08' v, '국내주식' n, 8 s FROM dual) x
  ON (t.GRP_CD=x.g AND t.CD_VAL=x.v) WHEN NOT MATCHED THEN INSERT (GRP_CD,CD_VAL,CD_NM,SORT_NO,USE_YN) VALUES (x.g,x.v,x.n,x.s,'Y');
MERGE INTO CD_COMMON t USING (SELECT 'PART_CD' g, 'P09' v, '본사후선' n, 9 s FROM dual) x
  ON (t.GRP_CD=x.g AND t.CD_VAL=x.v) WHEN NOT MATCHED THEN INSERT (GRP_CD,CD_VAL,CD_NM,SORT_NO,USE_YN) VALUES (x.g,x.v,x.n,x.s,'Y');
MERGE INTO CD_COMMON t USING (SELECT 'PART_CD' g, 'P10' v, '미지정' n, 10 s FROM dual) x
  ON (t.GRP_CD=x.g AND t.CD_VAL=x.v) WHEN NOT MATCHED THEN INSERT (GRP_CD,CD_VAL,CD_NM,SORT_NO,USE_YN) VALUES (x.g,x.v,x.n,x.s,'Y');
