-- V010: DASH_RESOURCE UNIT_TYPE 값 확장 ('TEAM'/'PART' → 'ALL'/'DEPT'/'PART')
-- 주의: 기존 CHECK가 'ALL'을 막으므로 UPDATE 전에 반드시 제약을 먼저 DROP한다.
ALTER TABLE DASH_RESOURCE DROP CONSTRAINT CK_DASH_RES_UNIT;
UPDATE DASH_RESOURCE SET UNIT_TYPE='ALL' WHERE UNIT_TYPE='TEAM';
ALTER TABLE DASH_RESOURCE ADD CONSTRAINT CK_DASH_RES_UNIT CHECK (UNIT_TYPE IN ('ALL','DEPT','PART'));
