-- V015: 업무사이트 모음 (WORK_SITE) — 업무용 사이트 바로가기 링크 (19c 호환)

CREATE TABLE WORK_SITE (
  SITE_ID     NUMBER        GENERATED BY DEFAULT AS IDENTITY,
  SITE_URL    VARCHAR2(500) NOT NULL,
  SITE_NM     VARCHAR2(100) NOT NULL,
  DESCRIPTION VARCHAR2(500),
  SORT_NO     NUMBER(5)     DEFAULT 0 NOT NULL,
  USE_YN      CHAR(1)       DEFAULT 'Y' NOT NULL,
  CREATED_AT  TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  CREATED_BY  VARCHAR2(30)  DEFAULT 'SYSTEM' NOT NULL,
  UPDATED_AT  TIMESTAMP,
  UPDATED_BY  VARCHAR2(30),
  CONSTRAINT PK_WORK_SITE PRIMARY KEY (SITE_ID),
  CONSTRAINT CK_WORK_SITE_USE_YN CHECK (USE_YN IN ('Y','N'))
);

-- 시드: 사내 업무 시스템 예시 (가상 주소). USE_YN='N' 1건 포함 — 필터 동작 확인용.
INSERT INTO WORK_SITE (SITE_URL, SITE_NM, DESCRIPTION, SORT_NO, USE_YN)
  VALUES ('https://gw.example.co.kr', '그룹웨어', '전자결재·메일·게시판 통합 그룹웨어', 1, 'Y');
INSERT INTO WORK_SITE (SITE_URL, SITE_NM, DESCRIPTION, SORT_NO, USE_YN)
  VALUES ('https://itsm.example.co.kr', 'ITSM SR관리', 'SR 등록·진행 현황 관리 시스템', 2, 'Y');
INSERT INTO WORK_SITE (SITE_URL, SITE_NM, DESCRIPTION, SORT_NO, USE_YN)
  VALUES ('https://devportal.example.co.kr', '개발자 포털', '배포·형상관리·API 문서 포털', 3, 'Y');
INSERT INTO WORK_SITE (SITE_URL, SITE_NM, DESCRIPTION, SORT_NO, USE_YN)
  VALUES ('https://wiki.example.co.kr', '사내 위키', '팀 문서·기술 위키', 3, 'Y');
INSERT INTO WORK_SITE (SITE_URL, SITE_NM, DESCRIPTION, SORT_NO, USE_YN)
  VALUES ('https://old-gw.example.co.kr', '구 그룹웨어', '구버전 그룹웨어(사용 중지)', 4, 'N');
