-- V016__create_dml_tables.sql
-- DML 점검·개선 관리: 기간계 DML성 SR(유형 18/19) 스냅샷 + 사용자 점검/개선 입력.
-- 스냅샷(배치 소유)과 사용자 입력을 분리해 매주 배치 재실행이 사용자 입력을 덮지 않게 한다.
-- Oracle 19c 호환 DDL (플래그는 CHAR(1) 'Y'/'N', BOOLEAN 미사용).

CREATE TABLE DASH_DML_SR (
  SR_NO            VARCHAR2(11)  NOT NULL,
  BASE_YM          VARCHAR2(6),
  SR_TPCD          VARCHAR2(2),
  SR_TPCD_NAME     VARCHAR2(40),
  BSWR_DETL_NAME   VARCHAR2(100),
  SR_REG_STAT_CODE VARCHAR2(2),
  TITL_CNTT        VARCHAR2(400),
  MSG_CNTT         VARCHAR2(2048),
  CUST_INFO_YN     VARCHAR2(1),
  RQSR_EMPNO       VARCHAR2(9),
  RQSR_NM          VARCHAR2(40),
  RQSR_DPCD        VARCHAR2(4),
  TRTH_RQST_NM     VARCHAR2(40),
  TRTH_RQST_DPCD   VARCHAR2(4),
  PIC_EMPNO        VARCHAR2(9),
  PIC_NM           VARCHAR2(40),
  PIC_DPCD         VARCHAR2(4),
  PIC_DPNM         VARCHAR2(40),
  DEV_DEPT_CD      VARCHAR2(30),
  DEV_PART_CD      VARCHAR2(30),
  REG_DATE         VARCHAR2(8),
  RFLC_SCDL_DATE   VARCHAR2(8),
  PROS_CMPT_DATE   VARCHAR2(8),
  SYNCED_AT        TIMESTAMP,
  CREATED_AT       TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CREATED_BY       VARCHAR2(30),
  UPDATED_AT       TIMESTAMP,
  UPDATED_BY       VARCHAR2(30),
  CONSTRAINT PK_DASH_DML_SR PRIMARY KEY (SR_NO)
);

CREATE INDEX IX_DASH_DML_SR_SCOPE ON DASH_DML_SR (BASE_YM, DEV_DEPT_CD, DEV_PART_CD);

CREATE TABLE DASH_DML_CHECK (
  SR_NO          VARCHAR2(11) NOT NULL,
  CHECK_YN       CHAR(1) DEFAULT 'N' NOT NULL,
  IMPROVE_YN     CHAR(1) DEFAULT 'N' NOT NULL,
  IMPROVE_PLAN   VARCHAR2(2000),
  PLAN_CMPT_DATE VARCHAR2(8),
  CMPT_YN        CHAR(1) DEFAULT 'N' NOT NULL,
  REMARK         VARCHAR2(1000),
  CREATED_AT     TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CREATED_BY     VARCHAR2(30),
  UPDATED_AT     TIMESTAMP,
  UPDATED_BY     VARCHAR2(30),
  CONSTRAINT PK_DASH_DML_CHECK PRIMARY KEY (SR_NO),
  CONSTRAINT FK_DASH_DML_CHECK_SR FOREIGN KEY (SR_NO) REFERENCES DASH_DML_SR (SR_NO),
  CONSTRAINT CK_DML_CHECK_YN   CHECK (CHECK_YN   IN ('Y','N')),
  CONSTRAINT CK_DML_IMPROVE_YN CHECK (IMPROVE_YN IN ('Y','N')),
  CONSTRAINT CK_DML_CMPT_YN    CHECK (CMPT_YN    IN ('Y','N'))
);
