-- V017: 비밀번호 정책 컬럼 추가 (19c 호환, additive). 기존 V007 무수정.
ALTER TABLE AUTH_ACCOUNT ADD (
  STATUS_CD           CHAR(2)       DEFAULT '00' NOT NULL,
  PASSWORD_CHANGED_AT TIMESTAMP,
  PREV_PASSWORD_HASH  VARCHAR2(100)
);
-- 상태 코드: 00 정상 / 01 잠금(10회 실패) / 02 휴면(3개월 미사용)
ALTER TABLE AUTH_ACCOUNT ADD CONSTRAINT CK_AUTH_STATUS CHECK (STATUS_CD IN ('00','01','02'));
-- 백필: 기존 계정은 배포 직후 즉시 만료/휴면되지 않도록 변경일시를 현재로 설정.
UPDATE AUTH_ACCOUNT SET PASSWORD_CHANGED_AT = SYSTIMESTAMP WHERE PASSWORD_CHANGED_AT IS NULL;
