-- 파트 취합본(DASH_WKLY_SUM) 주당 다건 허용: (WEEK_YMD, DEPT_CD, PART_CD) UK 제거.
-- 조회 성능을 위해 동일 컬럼 조합의 비유니크 인덱스로 대체한다. 19c 호환 DDL만 사용.
ALTER TABLE DASH_WKLY_SUM DROP CONSTRAINT UK_DASH_WKLY_SUM_WK_PART;

CREATE INDEX IX_DASH_WKLY_SUM_WK_PART ON DASH_WKLY_SUM (WEEK_YMD, DEPT_CD, PART_CD);
