-- 파트 취합본-개인 보고 선택 링크(N:M). 업무리더가 선택한 개인 보고들이 취합본을 구성한다.
-- 부모(취합본/개인 보고) 삭제 시 링크는 FK ON DELETE CASCADE 로 자동 정리. 19c 호환 DDL만 사용.
CREATE TABLE DASH_WKLY_SUM_RPT (
    SUM_ID  NUMBER NOT NULL,
    RPT_ID  NUMBER NOT NULL,
    CONSTRAINT PK_DASH_WKLY_SUM_RPT PRIMARY KEY (SUM_ID, RPT_ID),
    CONSTRAINT FK_DASH_WKLY_SUMRPT_SUM FOREIGN KEY (SUM_ID) REFERENCES DASH_WKLY_SUM (SUM_ID) ON DELETE CASCADE,
    CONSTRAINT FK_DASH_WKLY_SUMRPT_RPT FOREIGN KEY (RPT_ID) REFERENCES DASH_WKLY_RPT (RPT_ID) ON DELETE CASCADE
);
CREATE INDEX IX_DASH_WKLY_SUM_RPT_RPT ON DASH_WKLY_SUM_RPT (RPT_ID);
